"""Initial migration.

Revision ID: 2e0a7b8f99fa
Revises: 
Create Date: 2022-05-11 22:07:58.157565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0a7b8f99fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('ayaya', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'ayaya')
    # ### end Alembic commands ###
