"""deleteemail1

Revision ID: 37b7aea4ba93
Revises: c62324a53293
Create Date: 2022-05-13 16:38:16.589026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b7aea4ba93'
down_revision = 'c62324a53293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'email1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('email1', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
