"""Initial migration1

Revision ID: 9d6f2793b695
Revises: 2e0a7b8f99fa
Create Date: 2022-05-11 22:08:24.709499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6f2793b695'
down_revision = '2e0a7b8f99fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'ayaya')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('ayaya', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
